### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by maddiesolis** [MarketMate-Seng480/MarketMate#151]
**Task**: We need to add a tab to the navbar that says "About" or "About Us". That page will contain Artisway's story (the team members, some info about the course, whatever else is necessary to include).

**To-do**:
- [ ] Write the About Us copy in a Google Doc
- [ ] Design the About Us page (optional)
- [ ] Implement the About Us page
- [ ] Ensure the page is responsive to different screen sizes
