### ISSUE TITLE
Checkout Documentation

### ISSUE THREAD

**Issue by maddiesolis** [MarketMate-Seng480/MarketMate#152]
**Task**: Currently, our checkout flow is confusing for users (found in our user testing sessions). We need to add some informative text throughout the site so people know how checkout works.

**To-do**:
- [ ] Write copy in Google Doc (so group can collaborate on it)
- [ ] Add informative text to Product Details (image below)
- [ ] Add informative text to Cart (image below)
- [ ] Add a confirmation modal that pops up when "Checkout" button is clicked
- [ ] Maybe change language of "Checkout" button (let's talk about this as a group)
- [ ] Maybe change the frontend language and iconography of "Cart" to something like "Basket"

![Image](https://github.com/MarketMate-Seng480/MarketMate/assets/105009134/9664a6a6-0e74-43bb-b4bd-72a9e34f9da2)

![Image](https://github.com/MarketMate-Seng480/MarketMate/assets/105009134/c59b49c5-9dcd-4ba2-89ad-c0b485804203)

![Image](https://github.com/MarketMate-Seng480/MarketMate/assets/105009134/2a6a1f4e-8a85-4e27-8a28-f68714de414f)
