### ISSUE TITLE
Add Loading States

### ISSUE THREAD

**Issue by maddiesolis** [MarketMate-Seng480/MarketMate#153]
**Task**: To create a more seamless user experience, we need to add loading states throughout the site. We already have loading spinners in some buttons, but will need to add spinners/skeletons to other parts of the website.

**To-do**:
- [ ] Identify all parts of the site that need loading states
- [ ] Use [Chakra UI Skeleton](https://chakra-ui.com/docs/components/skeleton/usage) for page loading states
- [ ] Use [Charka UI Spinner](https://chakra-ui.com/docs/components/spinner/usage) for buttons and any other places where a spinner is appropriate 
- [ ] Ensure all loading states are responsive to different screen sizes
