### ISSUE TITLE
Cleanup UI

### ISSUE THREAD

**Issue by maddiesolis** [MarketMate-Seng480/MarketMate#154]
**Task**: Go through the site and ensure everything is consistent (text, buttons, icons, images, etc.) and looks clean and professional.

**To-do**:
- [ ] Update homepage text colours to match designs
- [ ] Featured Vendors loads all vendors, should only include a select few (discuss with group)
- [ ] Featured Products loads all products, should only include a select few (discuss with group)
- [ ] Update navbar buttons styling, shouldn't be a pink box when clicked (refer to design)
- [ ] In All Vendors page, update filters dropdown styling (refer to design)
- [ ] Update store tags styling, create a CustomTag component to be used throughout site (refer to design)
- [ ] Update Vendor Details page so it looks better on desktop
- [ ] Add location indicator to navbar, make sure this is responsive and shows on mobile view
- [ ] Update Cart styling so it matches design
- [ ] For all instances of a product image, make sure they are the same aspect ratio (product card, product management page, product image upload, product details, etc.)
- [ ] Change "Account" tab to "Personal Info"
- [ ] Update Account/Personal Info page so the button used is the same as in Storefront and Products pages
