### ISSUE TITLE
Vendor Verification Flow

### ISSUE THREAD

**Issue by maddiesolis** [MarketMate-Seng480/MarketMate#182]
**Task**:  To ensure legitimate vendors have storefronts on our website, we will use a manual verification process before new vendors can have a public storefront.

**Flow**:
1. User fills out "Become a Vendor" form.
2. On submit, we receive an email saying someone tried to sign up, user receives an email saying we will review their application.
3. After we look over their form (maybe the form info can be included in the email sent to us), we change the `isVerified` column in the `Vendor` table to `true` (or keep as false). We can also consider having three values (`pending`, `true`, `false`).
4. If they are set to `true`, their storefront automatically becomes public and we notify them via email.

**Notes**:
- Communication is important here (let them know why we want to review their application, it is for safety and ensuring authentic vendors are signing up)
- We can automate some of the email communication but do other parts manually (like notifying them that their application has been approved)
- If a user seems legit, but their storefront is poorly set up, do we want to get involved and suggest that they make their photos better, add a logo/banner if they don't have one, etc.? How much do we want to make our feel autonomous to them versus having our team's involvement? Would it be an asset or hinderance?

**To-do**:
- [ ] Add `isVerified` column to the `Vendor` table (could be boolean but might be easier if it is string that only gets `true`, `false`, or `pending`
- [ ] On "Become a Vendor" form submit, send automatic email using Resend to both vendor and info@artisway.ca
- [ ] If we can figure out how, connect code to Google Sheets so an entry is added for us to keep track of vendor applications in table form
- [ ] Add "Pending" or "Public" tab to Storefront and Products admin pages (Account page can be kept the same because they can still purchase other products)
- [ ] When `isVerified` is `true` show "Public" tag, when `isVerified` is `false` or `pending` show "Pending" tag
- [ ] When `isVerified` is switched to `true` either send an email manually (we can create a template for us to use) or automate an email (will need to figure out how we can connect Supabase to Resend)
